spring.application.name=tournment
spring.datasource.url=jdbc:mysql://localhost:3306/freefire
spring.datasource.username=root
spring.datasource.password=Shiva@321?
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=kouluyshiva@gmail.com
spring.mail.password=jioa fkjq libt yafs

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
